apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/platformnavigator/variants/cloudprovider/azure-nfs
- ../../../../components/platformnavigator/variants/enable-hostnetwork
resources:
- ../../../../components/platformnavigator/base